### ISSUE TITLE
Wind plotting issues

### ISSUE THREAD

**Issue by nwagenbrenner** [firelab/windninja-mobile#117]
In some cases the spacing between wind vectors appears to be variable across the domain at a given zoom level. Another tester asked about this and then I just noticed this case below where it's pretty obvious. What's going on here and is this something that could/should be fixed? 

![screenshot_20160628-130722](https://cloud.githubusercontent.com/assets/3696653/16429013/e7df9600-3d31-11e6-8a43-c09fc772c7d0.png)

Also, sometimes the whole screen doesn't render at the appropriate zoom level. The only way I could get out of the zoom mismatch shown below was to pan around and zoom out and in again. I know this was looked into before, but maybe there's something else that could be done?

![screenshot_20160628-130743](https://cloud.githubusercontent.com/assets/3696653/16429137/7ce18772-3d32-11e6-9855-d4df932ecce4.png)

**Comment by fspataro** [comment]
you'll need to capture the job data or at least the job spec so we can investigate the details of what's going on.  My first guess it that those missing arrows don't have a color symbol for some reason.... most likely they are exactly on the split for the green/blue range and it doesn't know which color to put them as... but that's just a guess. 

For the second situation, there must be some step or user action previous that's causing the zoom to be out of sync.  So we'll need try to notice what else was done when this occurs.  We could add some sort of bulk refresh but the layer is a simple tile layer so something is interrupting the draw phase and then the layer thinks it's already has the tiles in place.

**Comment by nwagenbrenner** [comment]
The job is attached.

[job.zip](https://github.com/firelab/windninja-mobile/files/337903/job.zip)

**Comment by ksshannon** [comment]
The top one *might* have to do with the clustering algorithm.  Note that gaps appear frequently where the vectors (likely buffered) envelope overlaps with a neighbor's envelope after a series of uniform directions. I have no clue, but it might be a place to look.

**Comment by fspataro** [comment]
Yeah, the clustering algorithm would explain the non-standard grid layout in that picture.  Unfortunately, I don't think we don't have much control over the clustering unless we manually build the different levels ourselves.  We'll dig a little deeper... Is this picture the lowest level? Do we see it at any other level?

**Comment by nwagenbrenner** [comment]
This is the highest resolution, but it happens at other levels too.

**Comment by ksshannon** [comment]
No, the lowest level is a perfectly uniform grid (at least for me).  Big Southern Butte is a good test, or really any relatively flat area.  It can happen on any of the levels, as far as I could tell.

**Comment by nwagenbrenner** [comment]
For the job I reported on and attached (Bigsky), it happens at multiple levels. Although it's most obvious at the highest resolution, which is what I posted in the picture.

**Comment by ksshannon** [comment]
Sorry, if you zoom in far enough at the highest resolution, it goes away, but this is because the vectors stop overlapping.

**Comment by nwagenbrenner** [comment]
Here's another screen capture demonstrating the issue from a run on big southern butte that Kyle mentioned. This is the 3rd from the lowest zoom level. 

![screenshot_20160628-155907](https://cloud.githubusercontent.com/assets/3696653/16433852/8dcc78b4-3d49-11e6-8397-2d6b871d86a0.png)

**Comment by fspataro** [comment]
Ok, we verified it's the 'clustering' algorithm in mapnik that's the issue.  Again unfortunately there's no real control for this other than on/off.  There are a couple of things we can try:

1. The arrow images are not square, so when they rotate they create much more diversity in when overlap occurs.  Adjusting the images to squares might reduce the effects to a tolerable level.  

2. Using SVG format might. This could also reduce the impact of non-visible space that overlaps since the SVG format doesn't contain "blank" pixels as the png format. 

3. Create our clustering algorithm, this would be the only foolproof and exact solution but adds some more processing time to the whole thing. 

4. Live with it as is for the short term and continue prototyping the vector-tile technology which is getting more robust and has reach production level in a number of the GIS products. 

5. Any other cartographic tricks or techniques support by mapnik?  You can download tillmill and play with the styling manually to see if anything works better.

**Comment by fspataro** [comment]
well, neither 1 or 2 provide any significant improvement.  Basically anywhere the arrows are parallel or nearly parallel and closer to vertical/horizontal, the renderer can fit more arrows into the space.  So far I can't find any setting that would specify a discrete interval to use.  

With the full dataset and tiles, we'll probably have to write our own clustering preprocessor.  Which isn't too big of deal, it will add a little time to the overall job but probably not that much.  More files will be created on disk, again probably not a huge amount or a big overall issue.  It will take some time to create and test the clustering process but we might be able to use some raster tricks to resample at the various levels.  The up side is that each clustered arrow would/could be an aggregate of the represented area rather than just the first/discrete value. So the result would be more accurate visualization.

**Comment by nwagenbrenner** [comment]
Okay, thanks for looking into this. I think at this point we would prefer the current display as opposed to adding computational time. The raster tiling is already the bottleneck in the simulations. @jforthofer ?

**Comment by jforthofer** [comment]
Yeah, to me this problem isn't that big of a deal...  the colors are still accurate right?  It just fills in vectors in a way that makes them not be a perfect row/column grid.
Maybe if we rethink the whole tiling stuff to speed it up we might also resolve this problem?
