### ISSUE TITLE
Time zone is missing from time stamps

### ISSUE THREAD

**Issue by nwagenbrenner** [firelab/windninja-mobile#123]
The time zone used to be displayed in the time stamp. Was this removed intentionally? It might be a good idea to keep this in the display.

**Comment by CorbyHarkonnen** [comment]
yeah. I added a function for display dates so that they appear the same across devices (iOS has an odd output for date.toLocalString() that differs significantly from the android implementation). I can take a look at re-adding the timezone to the string. Do we want the simple MST/MDT type of timezone, or the offset from GMT (+7:00/+6:00)?

**Comment by jforthofer** [comment]
I'd say the simple MST/MDT is what our users would be most comfortable with.

**Comment by CorbyHarkonnen** [comment]
fixed in 1.0.1
