### ISSUE TITLE
Set up notification for new accounts that require approval

### ISSUE THREAD

**Issue by nwagenbrenner** [firelab/windninja-mobile#124]
If an email address is not auto-approved an email should be sent to wind.ninja.support to notify us that an account is pending approval. Someone just sent a note via "Feedback" to let us know they were still waiting for approval. I approved the account and emailed the user to let them know. I guess this will be our system for the short-term?

**Comment by jforthofer** [comment]
I don't know...  what do we base our approval on?  Do we get any info about why they want to use WindNinja?  Like for wildland fire purposes?  If not, are we just approving all of them?  And if so, should we just set up an auto-approval for all?  We could talk about this at the Tuesday meeting...

**Comment by nwagenbrenner** [comment]
Okay, I don't know what's going on here. There is one user that is unable to successfully register. Data/account/*.json reports the "status" as "pending." Changing this to "accepted" seems to have no effect. The user just keeps getting an error about registering the app.

I think our current process is supposed to just send an email to users that aren't on the auto approved list. Then the user has to click a link to complete the registration. This seems to be working for most people, but this is one case where it's failing. Maybe the user's email is blocking our email or marking it as spam or something. I'm waiting to hear back on whether the user ever got a registration email from us. 

Regardless, it seems like we should be able to manually complete the registration if this system fails. Is there something else that needs to be updated besides Data/account/*.json?

**Comment by fspataro** [comment]
1. Yes, the current process is that users are not "automatically" registered but are essentially "self" registered by clicking on the email link e.g. if you own the email account you registered with you can self register. 

2. We know some emails are still getting lost due to not having a true, registered email server. ie kyle's pobox (or whatever) never receives emails. So it's possible this is why the user never received the email.  We can probably confirm if the email got sent from the logs. 

3. Yes, you can manually set the account state by editing the account json file.  It should pick that change up right away.  You can confirm this change using the 'postman' utility or curl or simply a web browser since this is a simple get request.  Given that, it's possible the request/response got cached and needed something cleared before receiving the updated account status...not sure if this would have been on the client or server.  We can add some extra "no-cache" headers to the request/response messages.

**Comment by nwagenbrenner** [comment]
Okay. As far as I know, everyone should be receiving emails from us now that we're using SES. Kyle get's emails from us now. At any rate, I suppose there's always a chance of an email not making it through, so as long as we can manually register people, I think we're good.

**Comment by fspataro** [comment]
Ok, i didn't realize the SES was connected.  i thought it wasn't available for the gov cloud?  If emails are routing thru SES, you should be able to see email logs and statistics so you can confirm the email went out via the SES management console.

**Comment by nwagenbrenner** [comment]
It's not available in govcloud, so we route the emails through another AWS instance where we have access to SES. It's Sam/Reggie's instance and SES account.

**Comment by fspataro** [comment]
Ah, makes sense now. 

If we want to see want happened here, first thing to check would be the SES manager and determine if an email got sent thru that system.  The docs for SES says there should be logs and status about each email.  So we should be able to determine if email got sent, then if delivered or bounced.
