### ISSUE TITLE
Wind vectors disappear when you zoom in on iOS

### ISSUE THREAD

**Issue by nwagenbrenner** [firelab/windninja-mobile#127]

**Comment by fspataro** [comment]
This is because the map can zoom further than we're generating tiles.  The default tile generation in the config is 14.  We can set the map to the same limit but that would prevent you from increasing the zoom level of the tile generation on the fly.  

It looks like the default tile generation is still 14.  Can you confirm this on the deployed server?  Config yaml file in the wrapper folder.

**Comment by nwagenbrenner** [comment]
But this doesn't happen on Android? On Android you can zoom in as far as you want on the map and the highest zoom level of the arrows is still displayed.

**Comment by fspataro** [comment]
Simply a difference in how the map control, tiles, javascript runs on the Android device.  Android appears to continue using the last set of tiles rather than clearing them off.  That's more a bug on the Android side than on the iOS side.  At levels, 15, 16, 17, there shouldn't be tiles.  iOS is correct.  Android is wrong. It's sort of useful bug for us but Android is not working correctly.

**Comment by nwagenbrenner** [comment]
Oh, okay, that's unfortunate.

**Comment by fspataro** [comment]
Actually, sorry Android and iOS builds were out of sync.  We turned off the "use intermediate tiles on error" for iOS to fix the weird display issue in #117 but Android.  So we can have the lower levels fill in with the setting on but it will also do the same for upper levels and you sometimes get issues like #117.  At this point it's an either or.

**Comment by nwagenbrenner** [comment]
I'd say leave it on so the vectors are viewable no matter how far you zoom in on the map. @jforthofer ?

**Comment by jforthofer** [comment]
Yeah, I'd say make it so the vectors are always viewable when you zoom in.

**Comment by CorbyHarkonnen** [comment]
rasters will (should) always show again. keep in mind that this will cause the same odd behavior we saw with issue #117 and some of the larger tiles not being replaced with the correct smaller tiles.

The other option to fix this would be to increase the raster creation for levels below 14 (current default on server), but this will increase the size of the downloads (quite significantly for levels 16 and 17)
