### ISSUE TITLE
Enable the momentum solver 

### ISSUE THREAD

**Issue by nwagenbrenner** [firelab/windninja-mobile#133]
We could either:

1. Add a button to toggle between CFD/mass-consistent solver. Requires users to know the difference between the two solvers.

or

2. Just have the CFD solver be the default (use it for all runs). Simpler, but we still don't know how much use to expect and how much this might slow things down.

**Comment by nwagenbrenner** [comment]
@fspataro the issue is that the subprocesses aren't finding the OpenFOAM installation. Can we set the following when the WindNinja_cli is called: 

    export FOAM_INST_DIR=/home/ubuntu/src/                                                                                                                                 
    foamDotFile=$FOAM_INST_DIR/OpenFOAM-2.2.x/etc/bashrc                                                                                                                   
    [ -f $foamDotFile ] && . $foamDotFile

I think that should fix it. For example, this script will run from the job directory as root (and it will only run with that extra export block):

    #!/bin/bash                                                                                                                                                            
                                                                                                                                    
    export FOAM_INST_DIR=/home/ubuntu/src/                                                                                                                                 
    foamDotFile=$FOAM_INST_DIR/OpenFOAM-2.2.x/etc/bashrc                                                                                                                   
    [ -f $foamDotFile ] && . $foamDotFile                                                                                                                                  
                                                                                                                                                                       
    WindNinja_cli cli_momentumSolver_diurnal.cfg

**Comment by fspataro** [comment]
@nwagenbrenner options:

1. Can we use the existing config items to tweak how the cli is executed (see test steps below)
2. Create a "batch script" that accepts the normal wncli parameters, executes these lines then passes thru the parameters to the cli.  Basically what you've go above but pass thru the parameters not the cfg file.
3. I'll need to update the function that executes the cli to handle multiple commands 

1 and 2 can probably be tested out quickly.  It will take a bit to get to 3.

Test steps for 1:
in windninjawrapper.config.yaml wn_cli section
1. uncomment and use the env (list) config for the export, so:

wn_cli
  ...
  env:
    - FOAM_INST_DIR=/home/ubuntu/src/

2. in the path config item, chain all the rest together

wn_cli
  ...
  path:  foamDotFile=$FOAM_INST_DIR/OpenFOAM-2.2.x/etc/bashrc && [ -f $foamDotFile ] && . $foamDotFile && /usr/local/bin/WindNinja_cli


This chain might not work but it's worth a quick test to see if it covers the issue for the moment.  Otherwise, i'll need to write the function that

**Comment by fspataro** [comment]
@nwagenbrenner it looks like you hardcoded in the OpenFoam commands.  Were you able to try from the config?

**Comment by nwagenbrenner** [comment]
I just added the commands to set the OpenFOAM environment when the CLI is called. I didn't try anything else.

**Comment by fspataro** [comment]
ok, I tested setting it up in the config file rather than hard coded in the wncli.py and it seems to work the same so I reset it to the config.  This way it's easier to manipulate... both settings are in the same place.
