### ISSUE TITLE
Can't start new run when viewing one

### ISSUE THREAD

**Issue by jforthofer** [firelab/windninja-mobile#144]
If you are currently viewing wind vectors from a simulation, and then click the pen to define a new domain (without clearing the simulation you were viewing), you run into problems filling out the form for the new run (it basically won't let you get a cursor in the run name text box).

**Comment by fspataro** [comment]
Fixed... probably due to changes in the timeslider/legend that allows both to be open now - before only one could be open at a time.  Added "removeRun()" when clicking on the start draw button.  Also remove the slightly annoying "all layers have been removed" message ... that seems like overkill and slightly confusing in this case.

**Comment by nwagenbrenner** [comment]
Appear to be fixed.
