### ISSUE TITLE
Api error when i try to request simulation with rasters

### ISSUE THREAD

**Issue by JoseluDAM2000** [firelab/windninja-mobile#155]
When i send a job to the Dev server, it just fail. 
This are the messages from the server:
```
"messages": [
        "2019-02-19T13:40:23.671346 | info | job created",
        "2019-02-19T13:40:26.818615 | info | Initializing WindNinja Run",
        "2019-02-19T13:40:26.847297 | info | DEM created",
        "2019-02-19T13:42:02.672551 | info | WindNinjaCLI executed",
        "2019-02-19T13:42:20.724549 | info | Output converted to geojson",
        "2019-02-19T13:42:21.860447 | info | TopoFire tiles compiled",
        "2019-02-19T13:42:21.928019 | error | list index out of range",
        "2019-02-19T13:42:21.928658 | info | Complete - total processing: 0:01:55.111698"
    ]
```
Im using the imputs from here: https://github.com/firelab/windninja-mobile/blob/master/WindNinja-Server/Docs/Web_API.md#200-job-details

**Comment by fspataro** [comment]
Hi, 
Can you pass me the job id, I'll check the detailed log on the server.  I don't think the DEV server is configured to generate the "raster" tileset package since it was built to test the new "clustered" output. 

Also you can try this setting for the products parameters:

"products":"vector:true;raster:false;topofire:false;geopdf:false;clustered:true;weather:true"

I'll add this to the API doc:

products parameter is a semi-colon delimited key value pair list.  The key-value pair is delimited with a colon:

product_code : true / false ; product_code : true / false ; product_code : true / false ; ...

Available products to generate:

- **vector** = GeoJson files of the WindNinja output . One file for each time simulation
- **raster** = Mapnik generated tileset based on the WindNinja output shapefiles.  One tileset for each time simulation, all packaged in a zip file. 
- **topofire** = Basemap tileset for the job domain extracted from the UofM TopoFire tile service
- **geopdf** = Not implemented as of yet, placeholder for future development
- **clustered** = This is a custom csv-like generated format of raw numerical data.  The file contains "scaled" levels of detail.  The format is parse-able by any client but was designed specifically for the WindNinja Mobile application for download size and rendering speed. 
- **weather** = GeoJson files of the large scale weather data downloaded and input to the WindNinja CLI for the job domain. One file for each time simulation

**Comment by JoseluDAM2000** [comment]
Here is:
af7b58be-ba70-4232-9c58-7c4fd55836ef

Can you reply this issue or something when you have the "raster" malfunctionality solved?

**Comment by fspataro** [comment]
Thanks, it's definitely something in the raster generation.  I'm digging a little deeper.  It does look most of the tile maker is installed so it might be something else.  Couple of things:

1. The raster tile generator is a big performance hit, we might disable it in the future.  What is your display client/use case? We might have a better "product" for you to use.

2. There are two typo in your job request: 
  a. there's an extra quote character at the end of the products: weather:true\"
  b. the mesh choice key has an extra "sa"

I don't think these are causing the error but would result in not getting back exactly what you expect. 

![image](https://user-images.githubusercontent.com/5933821/53669375-1fbda900-3c34-11e9-8aae-795650ce9d38.png)

**Comment by fspataro** [comment]
ok, turns out the extra quote in the products was causing the weather files to be skipped (ie false) and there was error in the tilemaker looking for the max wx speed which wasn't calculated.   Also a couple of mods from a local commit weren't sync'd from the last big update that starts the deprecation of the raster product so I didn't fully test the raster pipeline.  It seems to run this job correctly now. 

@nwagenbrenner is modifying the test server to run the momentum solver so you'll have to wait until she's done with that update to verify the fix there.

**Comment by JoseluDAM2000** [comment]
We use the rasters as a web layer to represent the simulation.
The server still having troubles to simulate. Check the sim **41b58946-584d-46d7-b974-65c89124f900**.

**Comment by fspataro** [comment]
Ok, either I forgot to move the edits over to the deployed app folder or we overwrote them with a stale git repo while patching the momentum solver.  

Give it another try...

Once we fully put the momentum solver in place, we'll likely turn off the raster output as those two combined are really heavy on the server and jobs will take awhile to generate.  You'll be better off using the vector product geojson files in a web browser.   OpenLayers, Leaflet, ArcGIS all have native support for the geojson output.

**Comment by jramireztsyl** [comment]
Thanks Fred, Joaquin at Technosylva here.
We have to talk about losing the tiles. We have done a performance test on rendering the geojson files on mobile at it just simply can not do it. It might draw the first 1 hour, but the performance is terrible. We really need the tiles. I'll discuss with Natalie too. Thanks for the support!@

**Comment by fspataro** [comment]
Hi Joaquin, 
Right, on mobile devices the geojson files are a little too heavy, that's the exact reason for the "clustered" output product.  It's not a true GIS format but it's really easy to work with since it's just a simple dataset.   What mapping platform library are you using?  The main windninja mobile app is using OpenLayers so you can see how the data is converted to a map layer in the repo source.  I probably have an example of how it works with ArcGIS JS and Leaflet should be pretty similar..

**Comment by jramireztsyl** [comment]
Thanks Fred!
I'll let @JoseluDAM2000 and Santiago Monedero continue the conversation :)  Team is using the ArcGIS Runtime for QT. Thanks!

**Comment by SandiaDeDia** [comment]
Thanks Fred, I am Santiago from Technosylva. 
We use ArcGIS for QT on a 3D environment and as Joaquin says the performance using graphic overlays with some data Natalie sent us some time ago (around 20000 vectors per time step) is  horrible on a mobile device (in 2D is better but still not good enough). Right now our implementation is using tiles and it works very very smoothly so if it was possible to keep those tiles we would really really appreciate it.  
Thanks for the support.

**Comment by JoseluDAM2000** [comment]
The raster generation works perfectly now.
