### ISSUE TITLE
Forecast duration error

### ISSUE THREAD

**Issue by JoseluDAM2000** [firelab/windninja-mobile#160]
I run a job and the generated times count was one less than the indicated forecast duration.

Id: 4b9d4413-1255-4021-ae9a-13be19beeae4
![imagen](https://user-images.githubusercontent.com/22506382/55162796-dc8a2380-5168-11e9-94bc-a1b1e5117459.png)

**Comment by nwagenbrenner** [comment]
@JoseluDAM2000 This isn't an error. WindNinja will attempt to download how ever many forecasts are available/valid up to the number of hours from now specified by "forecast_duration". So if it's 0900 MDT and you request a forecast_duration of 4, WindNinja will download valid forecasts out to 1300 MDT. The HRRR generates hourly forecasts, but other models, such as NAM or GFS, have longer time steps. Also, if older forecasts are still sitting on the weather model server (say from 0800 MDT), we may also download those too. So, "forecast_duration" does not equal the number of forecast time steps that will be downloaded.

**Comment by fspataro** [comment]
Also the server doesn't return any "past" forecasts/simulations.  So if the job started right before the top of the hour and finished shortly after the top of the hour it might drop the earlier simulation since it's now "in the past".  

Let us know if you're seeing this consistently and I'll review but there are definitely cases where the counts don't match but the time frame should be covered.
