### ISSUE TITLE
email/text notification not working

### ISSUE THREAD

**Issue by nwagenbrenner** [firelab/windninja-mobile#25]
I selected both text and email notification, but never received either although the runs completed. I was not prompted to enter my email address or phone number this time.

**Comment by nwagenbrenner** [comment]
Now I see there is a separate settings section where the phone/email info must be entered. Once I filled that out both services worked properly. If this info isn't completed we probably should alert the user when they select those options.

**Comment by CorbyHarkonnen** [comment]
will disable notification options until email/phone number have been set in the Settings panel.

**Comment by nwagenbrenner** [comment]
Is it possible to prompt the user to fill out the settings tab when they open the app for the first time? Maybe just default to that page when the app is opened for the first time and ask them to fill out the info? Otherwise, it can be a hassle if you've already started setting up a run and then you get to the part about email/text notification and realize you don't have your profile set up (this just happened to me) and have to enter your info and start over. 

Maybe we can word the settings page in a slightly different way so as to encourage (but not force) people to fill out their contact info and register their install. Something like "We recommend you provide your contact information so that we can notify you via email/text when your WindNinja simulations finish. You can return to this page at any time to fill in or update this information."

**Comment by jforthofer** [comment]
One way to do it would be to not gray out the email/phone alerts, and then if they do select to get an email/text alert a pop up window could tell them they have to set the email, phone number, etc. first.  The pop up could have a button to "Set contact info", which would take them to the page in settings where they do that.  After they set the info and hit OK, it could go back to the run settings panel they were at when they started all this.  Just an idea...

**Comment by jforthofer** [comment]
As Natalie said, it would also be good to open a special window the first time a user ever opens WindNinja.   It could say something like:
"Welcome to WindNinja.  We recommend you provide your contact information so that we can notify you via email/text when your WindNinja simulations finish.  This information can also be added or updated at any time from the settings tab."
The necessary fields (email, phone #, service provider) should be shown below, along with buttons "OK" and "No thanks".

**Comment by CorbyHarkonnen** [comment]
changed the initial popup window when launching the application to be a notice about entering name/email/phone for notification purposes and opening the settings panel to allow quick entry of details. This message will appear every time the application is launched and there is no configuration found (i.e. they have not clicked the 'Save' button in the settings panel - regardless of if they've filled out any info). I know this will probably be seen as a 'nuisance' reminder, but I figured it would be better to keep reminding the user rather than display the info once and have them potentially forget about it.

**Comment by nwagenbrenner** [comment]
Email/text notifications work now and the other stuff on this ticket is covered by #52 and #53.
