### ISSUE TITLE
Run Options tab is unpredictable

### ISSUE THREAD

**Issue by nwagenbrenner** [firelab/windninja-mobile#31]
When you click some of the buttons, the run options tab auto hides after the click. I think we should keep the tab open until the user clicks the "x" since there are multiple things the user might want to turn on/off here.

Sometimes the button doesn't do anything the first time it's clicked. For example, the Legend tab may not actually add the legend to the map the first time it's clicked, although it turns blue indicating that it has been clicked.

**Comment by CorbyHarkonnen** [comment]
part of this issue stems from the fact that there can only be one 'popup' on the screen at a time, currently there are only two popups (legend and forecast hour slider) so that makes things a bit easier, but there seems to be a timing issue when closing one before you can open another and I am looking into this currently, but I can definitely leave the Run Options panel open after clicking the buttons

**Comment by CorbyHarkonnen** [comment]
Run Options tab will now remain open when clicking on any of the buttons, I have also resolved the issue of the legend/forecast slider interchange
