### ISSUE TITLE
Need to limit the size of domains

### ISSUE THREAD

**Issue by jforthofer** [firelab/windninja-mobile#40]
We need to come up with a strategy to limit the size of domains that can be run. I just got a simulation going that was the size of western mt, it appears to be trying to do the simulation, so that's no good.

**Comment by jforthofer** [comment]
I got a text message about 3 hours later that the large simulation described above finished, but I'm not going to try to download it because I'm sure it's huge.
If the WindNinja resolution is set to something like "fine", then the actual simulation results won't be big...  but the DEM that had to be loaded must have been huge, and also the TopoFire map for offline mobile use would be really huge, so these are the issues we need to worry about.  We should just set a "max area" (north-south extent size times the east-west extent size) like we discussed at the last GCS meeting.  Can this limiter be implemented on the phone side of things, or does it have to be done on the server?  Phone seems like it'd be best if it can be done easily, but GCS would know best here...

**Comment by fspataro** [comment]
Yes... but that's really an decision for the Firelab staff.  GCS can provide any metrics and options to help with the decision but it really comes down to what's appropriate for your users.  

For the "Big" simulation started Thrusday night:
The processes ran for 4 hours but failed due to too many files for TopoFire zip - the 64 bit zip utility would allow for this sub-process to finish - but it's a good indicator that extent was too large... The zip file was already at 1.5 GB when it stopped.  The full download for the TopoFire was 2.9 GB and 126K files.  

We can do the check for "size" at either the client or server.  At the client, we'd get "quicker" feedback to the user and they could re-adjust before submitting the job.  At the server, we'd be able to make real-time tweaks to the parameter limits without republishing the app but the workflow for an "over the limit" job would be clunky.

Items to make decisions on:
1. Client side or server side limit checking?
2. Max 'area of interest' size
2a.  Do we factor in the number of forecasts?  For the TopoFire package, only the extent matters since it's a single unit.  But the "wind-ninja simulation" package will be mutlitpled but the number of iterations as well.  A user could easily overload the job engine by running a small AOI without a larger number of forecast hours.

**Comment by jforthofer** [comment]
1.  Let's do the limiting on the client side.
2.  Let's try 30 miles x 30 miles (so 900 sq. miles).  If needed, we can adjust this after some testing.
3.  Let's not account for the number of forecasts right now and see how it goes.

**Comment by fspataro** [comment]
Great, thanks!  

We also discussed changing the mesh/grid depending on the AOI size.  Do we want to take a stab at that now?  That would be implemented on the server side so it could really be adjusted at anytime.

**Comment by jforthofer** [comment]
Do you know how that is being done right now...?  In the input file read into WindNinja are we specifying the grid resolution using "coarse", "medium", "fine" or are we actually specifying a custom resolution (ie. a cellsize in meters)?

The thing that will probably be the limiting factor here would probably be the bandwidth since the files will grow in size if we increase the resolution (the increased computation time won't likely be as much of an issue I don't think).  So because of that, right now I'm leaning towards not messing with the resolution unless someone has a strong opinion the other way...

**Comment by fspataro** [comment]
Right now we're running with "fine" so it's probably a good indicator of high end anyway.  The "fine" parameter is enabled as one that CAN be sent from the client but it's currently hardcoded at the server as default = "fine" if the client doesn't specify.  

Actually it's really not the limiting factor since the simulations compute faster than generating tiles and the extent is the primary factory in size of the final package size. So we can probably leave it for later.

**Comment by jforthofer** [comment]
Sounds good to me...

**Comment by fspataro** [comment]
Quick test of a 30mi x 30mi AOI  --- approx Lolo to Stevensville N/S and 93 to Lolo pass E/W so a pretty large area:

TopoFire package = 18MB
Per forecast hour simulation result package 5.5MB 
About 4 minutes to from start to finish. 

So this seems like a reasonable starting point. I think we might have used 50mi sq for the limit in some of our original web based demos but we we're doing mobile download.

**Comment by CorbyHarkonnen** [comment]
set current limit to 900 sq mi (2331 sq km)
