### ISSUE TITLE
Should legend/arrow coloring be synchronized across simulation results for a single job? 

### ISSUE THREAD

**Issue by fspataro** [firelab/windninja-mobile#44]
I was running some tests the other day when the Hellgate winds were really whipping down thru the canyon and was looking for the time when they tailed off but it was difficult to determine b/c there was "always" a good portion of red arrows as I looped thru each result.  This is b/c the 5 group classification is specific to each result rather than a static.

Maybe this makes sense to the field users but to me it seems like the classification should have some consistency when comparing time frames.  If not a completely static classification, at least relative to each job set as a whole... that way when you look at the next/previous result RED is the same value.  Otherwise you HAVE to look at the legend for each result AND do the mental gymnastics of comparing a RED value in one result to a YELLOW or other color in different result.

**Comment by jforthofer** [comment]
I think this makes a lot of sense...  How about if we fix the color scale per job set?  I don't really want to permanently fix it since there is a big range of speeds across the country that people might be simulating and want to look at.  For example, someone in California might be simulating a Santa Ana wind of 50+ mph and someone else might be looking at the very light diurnal winds around Missoula (say < 10 mph).

Lets fix the color scale per job set...  great idea Fred!

**Comment by fspataro** [comment]
Great, I agree a static set doesn't make sense either but the job relative set seems like the right middle ground... we'll plug it in an see what it looks like.
