### ISSUE TITLE
consider removing forecast hours to download slider bar

### ISSUE THREAD

**Issue by nwagenbrenner** [firelab/windninja-mobile#50]
Let's remove this from the runs tab unless there is an issue with loading too many timesteps at once.

**Comment by CorbyHarkonnen** [comment]
there is still an issue of loading more than 5 timesteps at once crashing the app. I'm still not 100% sure as to the root cause (possibly the amount of memory available from within the browser).

I guess the question then becomes: is greater than 5 timesteps in a single run a standard occurrence. or is the typical usage more along the lines of 3-4 (pulling numbers randomly here), or does it vary a bunch?

**Comment by nwagenbrenner** [comment]
People will commonly want to view more than 5 timesteps, so it would be good to figure out a way to resolve this. Until then, we should limit the number that can be viewed to something smaller than what will crash the app.

**Comment by gcshollow** [comment]
We're currently testing, but it appears we can use as many as needed

**Comment by CorbyHarkonnen** [comment]
we can throw as many time steps on the map as we want now with the raster setup. removed the time slider and adding a run to the map will add all time steps
